### ISSUE TITLE
Slowness in loading of page and Images not loading

### ISSUE THREAD

**Issue by Uvarsni** [vnbaaij/ImageProcessor.Web.Episerver#57]
When opening a page, it takes very long time to load fully and few images are not rendered in the site. We are seeing 404 dependency errors.
Kindly suggest solution to overcome the issue.

**Comment by vnbaaij** [comment]
My guess is it is in your config but you supply to little detail to be sure. Also 404 errors on what dependencies?

**Comment by Uvarsni** [comment]
Thank you for coming back,
It is similar to issue #54 and we checked the config files and could see that is same as in the various comments posted.
 HEAD {environment name} are giving 404, getting dependency errors in Application Insight.
version : 5.6.5.15612

**Comment by vnbaaij** [comment]
Well, the latest versions are in the 5.7 range, so I would definitely update to those. 

As explained in #54, the 404's are being caused by the check of a file (procesed image) already exists. This is part of the mechanism and not something I can change. Sorry, but I don't work with (or at) Episerer anymore and don't have enough resources to research further.
